services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: next-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend/db.db:/app/backend/db.db
    restart: unless-stopped

networks:
  default:
    driver: bridge
